<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class customerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customer')->insert
        ([
            ['fname' => 'เทพ',
            'lname' => 'เมฆาอัคคี',
            'email' => 'Maka007@gmail.com',
            'phone_no'=> '0987456321',
            'address' => '',
            'province' => 'กรุงเทพ',
            'zipcode' => '22000',
            'location' => '1.1.10',
            'password' => hash::make('password'),
        ],
        ['fname' => 'จอร์น',
        'lname' => 'วิค',
        'email' => 'JohnWick007@gmail.com',
        'phone_no'=> '0985764123',
        'address' => '',
        'province' => 'กรุงเทพ',
        'zipcode' => '22000',
        'location' => '1.2.10',
        'password' => hash::make('password'),
    ],
    ['fname' => 'แฮรี่',
    'lname' => 'พอตเตอร์',
    'email' => 'Harry007@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.3.10',
    'password' => hash::make('password'),
],
['fname' => 'ลุงเม่ง',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'mei007@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.4.10',
    'password' => hash::make('password'),
],
['fname' => 'ลุงชัย',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'mei007@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.5.10',
    'password' => hash::make('password'),
],
['fname' => 'ป๊าแป๊ะ',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'wuw007@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.6.10',
    'password' => hash::make('password'),
],
['fname' => 'อาเทอร์',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'wuw006@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.7.10',
    'password' => hash::make('password'),
],
['fname' => 'อาชัย',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'wuw004@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.8.10',
    'password' => hash::make('password'),
],
['fname' => 'อาชู',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'wuw004@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.9.10',
    'password' => hash::make('password'),
],
['fname' => 'อาชี',
    'lname' => 'บ้านแป๊ะ',
    'email' => 'wuw004@gmail.com',
    'phone_no'=> '0982136547',
    'address' => '',
    'province' => 'กรุงเทพ',
    'zipcode' => '22000',
    'location' => '1.10.10',
    'password' => hash::make('password'),
],
        ]);
    }
}
